apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-gateway.fullname" . }}
  labels:
    app: {{ include "auth-gateway.name" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "auth-gateway.name" . }}
  ports:
    - port: {{ .Values.service.port }}   # external port on the internal LB
      targetPort: 8000                  # container port
      protocol: TCP
      name: http
