apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auth-gateway.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
