{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "notes-service.fullname" . }}-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
    kind: ClusterSecretStore
  target:
    name: {{ include "notes-service.fullname" . }}-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
        property: password
{{- end }}

