apiVersion: v1
kind: Service
metadata:
  name: {{ include "notes-service.fullname" . }}-preview
spec:
  type: ClusterIP
  selector:
    app: {{ include "notes-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http

